/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.12.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as ai_gemini from "../ai/gemini.js";
import type * as ai_openai from "../ai/openai.js";
import type * as auth_auth from "../auth/auth.js";
import type * as auth_users from "../auth/users.js";
import type * as chatbook_chunks_codebase from "../chatbook/chunks/codebase.js";
import type * as chatbook_chunks_documentation from "../chatbook/chunks/documentation.js";
import type * as chatbook_chunks_files from "../chatbook/chunks/files.js";
import type * as chatbook_chunks_youtube from "../chatbook/chunks/youtube.js";
import type * as chatbook_conversations from "../chatbook/conversations.js";
import type * as chatbook_embedding from "../chatbook/embedding.js";
import type * as chatbook_index from "../chatbook/index.js";
import type * as helper_chunks from "../helper/chunks.js";
import type * as helper_utils from "../helper/utils.js";
import type * as http from "../http.js";
import type * as quiz_chunks from "../quiz/chunks.js";
import type * as quiz_index from "../quiz/index.js";
import type * as quizify_quiz from "../quizify/quiz.js";
import type * as search from "../search.js";
import type * as utils_adapter from "../utils/adapter.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  "ai/gemini": typeof ai_gemini;
  "ai/openai": typeof ai_openai;
  "auth/auth": typeof auth_auth;
  "auth/users": typeof auth_users;
  "chatbook/chunks/codebase": typeof chatbook_chunks_codebase;
  "chatbook/chunks/documentation": typeof chatbook_chunks_documentation;
  "chatbook/chunks/files": typeof chatbook_chunks_files;
  "chatbook/chunks/youtube": typeof chatbook_chunks_youtube;
  "chatbook/conversations": typeof chatbook_conversations;
  "chatbook/embedding": typeof chatbook_embedding;
  "chatbook/index": typeof chatbook_index;
  "helper/chunks": typeof helper_chunks;
  "helper/utils": typeof helper_utils;
  http: typeof http;
  "quiz/chunks": typeof quiz_chunks;
  "quiz/index": typeof quiz_index;
  "quizify/quiz": typeof quizify_quiz;
  search: typeof search;
  "utils/adapter": typeof utils_adapter;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
